# version: '3.8'

services:
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    networks:
      - fastapi-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - fastapi-network
    volumes:
      - ./frontend/src:/app/src
      - nodemodules:/usr/local/apps/myapp/dev/node_modules/

networks:
  fastapi-network:
    driver: bridge

volumes:
  nodemodules: {}
