import { Post, PostRecipe, Recipe } from '../api/types'

export const mockRecipe: Recipe = {
  recipeId: 20919,
  name: 'California Scampi',
  cookTime: '5M',
  prepTime: '10M',
  totalTime: '15M',
  description: 'Make and share this California Scampi recipe from Food.com.',
  images: [
    '"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/20/91/9/picPCmubd.jpg"',
  ],
  category: 'Lobster',
  tags: ['Very Low Carbs', 'Healthy', '< 15 Mins', 'Stove Top'],
  ingredientQuantities: ['1', '1', '2', '3', '1/4', '1/4', '1/4', '1', 'NA")'],
  ingredients: [
    'shrimp',
    'lobster',
    'butter',
    'olive oil',
    'garlic cloves',
    'Italian parsley',
    'white wine',
    'lemon',
  ],
  rating: 5,
  calories: 106.8,
  fat: 3,
  saturatedFat: 0.8,
  cholesterol: 148.9,
  sodium: 175.9,
  carbs: 1.6,
  fiber: 0.1,
  sugar: 0.3,
  protein: 16,
  servings: 6,
  instructions: [
    { instruction: 'Melt butter and oil together in sauté pan.', step: 1 },
    {
      instruction: 'Add garlic, sauté for one minute, and add shrimp.',
      step: 2,
    },
    {
      instruction:
        'Sauté for one minute, add wine, lemon juice, salt, and pepper.',
      step: 3,
    },
    {
      instruction: 'Sauté quickly while sauce reduces and shrimp turns pink.',
      step: 4,
    },
    { instruction: 'Do not overcook.', step: 5 },
    { instruction: 'Sprinkle with parsley before serving.', step: 6 },
    { instruction: 'Serve with sauce over noodles or rice.', step: 7 },
    { instruction: 'Garnish with lemon wedges.', step: 8 },
  ],
}

export const mockRecipeTwo: Recipe = {
  recipeId: 58,
  name: 'Low-Fat Burgundy Beef & Vegetable Stew',
  cookTime: '2H14M',
  prepTime: '30M',
  totalTime: '2H44M',
  description:
    'Make and share this Low-Fat Burgundy Beef & Vegetable Stew recipe from Food.com.',
  images: [
    'https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/58/picnE8qoe.jpg',
    'https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/58/picwiayaY.jpg',
    'https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/58/picAaGXgc.jpg',
    'https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/58/picD2ey4Z.jpg',
    'https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/58/picKtSTwb.jpg',
    'https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/58/picY2Aqui.jpg',
  ],
  category: 'Stew',
  tags: [
    'Vegetable',
    'Meat',
    'Low Cholesterol',
    'Healthy',
    'Free Of...',
    'Weeknight',
    '< 4 Hours',
  ],
  ingredientQuantities: [
    '1 1/2',
    '1',
    '1',
    '1/2',
    '1/2',
    '1',
    '1/2',
    '3',
    '5 1/2',
    '1',
    '2',
    '1',
  ],
  ingredients: [
    'beef eye round',
    'dried thyme leaves',
    'salt',
    'pepper',
    'ready-to-serve beef broth',
    'Burgundy wine',
    'garlic',
    'cornstarch',
    'frozen sugar snap peas',
  ],
  rating: 4.5,
  calories: 280.1,
  fat: 6,
  saturatedFat: 1.5,
  cholesterol: 66.9,
  sodium: 591.5,
  carbs: 22.4,
  fiber: 6.1,
  sugar: 9.2,
  protein: 29.8,
  servings: 6,
  instructions: [
    { instruction: 'Trim fat from beef, cut into 1-inch pieces.', step: 1 },
    {
      instruction:
        'In Dutch oven, heat oil over medium high hunt until hot. Add beef (half at a time) and brown evenly, stirring occasionally.',
      step: 2,
    },
    { instruction: 'Pour off drippings.', step: 3 },
    { instruction: 'Season with thyme, salt and pepper.', step: 4 },
    {
      instruction:
        'Stir in broth, wine and garlic. Bring to boil; reduce heat to low.',
      step: 5,
    },
    { instruction: 'Cover tightly and simmer 1 1/2 hours.', step: 6 },
    { instruction: 'Add carrots and onions.', step: 7 },
    {
      instruction:
        'Cover and continue cooking 35 to 40 minutes or until beef and vegetables are tender.',
      step: 8,
    },
    {
      instruction:
        'Bring beef stew to a boil over medium-high heat. Add cornstarch mixture; cook and stir 1 minute. Stir in sugar snap peas.',
      step: 9,
    },
    {
      instruction:
        'Reduce heat to medium and cook 3 to 4 minutes or until peas are heated through.',
      step: 10,
    },
  ],
}

export const testPosts: Post[] = [
  {
    postId: 1,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 1' },
    image: '',
    message: 'This is a test post',
    likes: [],
    dislikes: [],
    comments: [
      {
        message: 'comment 1',
        postId: 1,
        userId: 1,
        commentId: 1,
      },
      {
        message: 'comment 2',
        postId: 1,
        userId: 1,
        commentId: 2,
      },
      {
        message: 'comment 3',
        postId: 1,
        userId: 1,
        commentId: 3,
      },
      {
        message: 'comment 4',
        postId: 1,
        userId: 2,
        commentId: 4,
      },
      {
        message: 'comment 5',
        postId: 1,
        userId: 2,
        commentId: 5,
      },
    ],
  },
  {
    postId: 2,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 2' },
    image: '',
    message: 'This is test post 2',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 3,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 3' },
    image: '',
    message: 'This is test post 3',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 4,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 4' },
    image: '',
    message: 'This is test post 4',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 5,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 5' },
    image: '',
    message: 'This is test post 5',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 6,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 6' },
    image: '',
    message: 'This is test post 6',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 7,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 7' },
    image: '',
    message: 'This is test post 7',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 8,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 8' },
    image: '',
    message: 'This is test post 8',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 9,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 9' },
    image: '',
    message: 'This is test post 9',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 10,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 10' },
    image: '',
    message: 'This is test post 10',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 11,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 11' },
    image: '',
    message: 'This is test post 11',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 12,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 12' },
    image: '',
    message: 'This is test post 12',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 13,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 13' },
    image: '',
    message: 'This is test post 13',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 14,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 14' },
    image: '',
    message: 'This is test post 14',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 15,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 15' },
    image: '',
    message: 'This is test post 15',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 16,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 16' },
    image: '',
    message: 'This is test post 16',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 17,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 17' },
    image: '',
    message: 'This is test post 17',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 18,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 18' },
    image: '',
    message: 'This is test post 18',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 19,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 19' },
    image: '',
    message: 'This is test post 19',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 20,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 20' },
    image: '',
    message: 'This is test post 20',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 21,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 21' },
    image: '',
    message: 'This is test post 21',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 22,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 22' },
    image: '',
    message: 'This is test post 22',
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    postId: 23,
    userId: 0,
    recipe: { recipeId: 58, name: 'Test 23' },
    image: '',
    message: 'This is test post 23',
    likes: [],
    dislikes: [],
    comments: [],
  },
]

export const testRecipes: PostRecipe[] = [
  {
    recipeId: 31,
    name: 'test 1',
  },
  {
    recipeId: 58,
    name: 'test 2',
  },
  {
    recipeId: 56,
    name: 'test 3',
  },
  {
    recipeId: 88,
    name: 'test 4',
  },
  {
    recipeId: 98,
    name: 'test 5',
  },
]

export const testRecipesTwo: PostRecipe[] = [
  {
    recipeId: 28,
    name: 'test 6',
  },
  {
    recipeId: 38,
    name: 'test 7',
  },
  {
    recipeId: 58,
    name: 'test 8',
  },
  {
    recipeId: 95,
    name: 'test 9',
  },
  {
    recipeId: 158,
    name: 'test 10',
  },
]
